### ISSUE TITLE
Transfer to fiji

### ISSUE THREAD

**Issue by hadim** [fiji/FilamentDetector#20]
I can't transfer it to Fiji because I don't have the permission.

@ctrueden I gave you access to the repo but I am not sure this is sufficient for you to do the transfer.

Let me know if I need to do something else.

**Comment by ctrueden** [comment]
Unfortunately, I don't have a Settings option here, so I can't transfer it myself. Can you go to https://github.com/fiji and accept the invite to join the org? Then see if you can transfer it. If not, I'll make you an owner temporarily, at which point you certainly will be able to.

**Comment by hadim** [comment]
Done. Thanks!
