### ISSUE TITLE
bump opencsv and scijava-pom

### ISSUE THREAD

**Issue by hadim** [fiji/FilamentDetector#21]
@ctrueden I am struggling to get JFX installed locally with java 1.8 on my Ubuntu 20.04.

Do you have it already set up on your side? If you do could do the bump for me, please?

If the bump is not backward compatible and requires more work I will take more time to fix it if you cannot.

Let me know.

**Comment by imagejan** [comment]
@hadim @ctrueden I bumped the version and adjusted the `CSVWriter` constructor signatures as necessary in #22.

I didn't yet test the functionality in Fiji though.
